[contact]
email = "example@email.com"
name = "Jane Doe"
phone = "+1-123-456-7890"

  [[contact.links]]
  link = "linkedin.com/in/janedoe"

  [[contact.links]]
  link = "github.com/janedoe"

[[education]]
degree = "Bachelor of Science in Software Engineering"
school = "University of Fictional"
suffixes = [ "Magna Cum Laude", "Research Distinction" ]

  [[education.details]]
  category = "Certificate"
  value = "Specialization in Data Science"

  [[education.details]]
  category = "Notable Achievements"
  value = "Dean's List (2018, 2019), Undergraduate Research Award"

  [education.dates]
  start = "2017-09-01"
  end = "2021-06-30"

  [education.location]
  city = "Imaginary City"
  state = "Stateville"

[[experience]]
company = "Tech Innovations Inc."
title = "Software Developer"
achievements = [
  "Developed a cloud-based storage solution improving data retrieval efficiency by 40%",
  "Collaborated on a team project to create a cross-platform mobile application"
]

  [experience.dates]
  start = "2021-07-01"

  [experience.location]
  city = "Imaginary City"
  state = "Stateville"

[[experience]]
company = "NextGen Solutions"
title = "Junior Developer"
achievements = [
  "Assisted in developing APIs for internal tools, improving workflow by 25%",
  "Participated in a hackathon and won second place for a machine learning project"
]

  [experience.dates]
  start = "2020-01-01"
  end = "2021-06-30"

  [experience.location]
  city = "Dreamtown"
  state = "Futureland"

[[skills]]
category = "Programming Languages"
value = "Python, Java, C++, JavaScript"

[[skills]]
category = "Tools & Frameworks"
value = "AWS, Docker, React, Node.js"

[[projects]]
name = "Personal Finance Tracker"
language = "Python, JavaScript"
details = "Developed a web application for personal finance management"
link = "https://github.com/janedoe/finance-tracker"
